import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const base = process.env.BLOG_TEST_URL ?? 'http://127.0.0.1:4330';
const browser = await chromium.launch({args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader']});
const errors = [];
try {
  const context = await browser.newContext({viewport: {width: 1280, height: 800}, deviceScaleFactor: 2, reducedMotion: 'reduce'});
  const page = await context.newPage();
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(`${base}/demos/2026/infinite-coast/`);
  await page.locator('astro-island[ssr]').waitFor({state: 'detached'});
  const zoom = () => page.locator('[data-coast-zoom]').innerText();
  const coords = () => page.locator('[data-coast-coordinates]').innerText();
  const canvas = page.getByLabel('曼德勃罗分形画布');
  await page.waitForTimeout(300);
  assert.equal(await zoom(), '缩放 1.00×');
  const initial = await canvas.screenshot();
  await page.mouse.click(600, 300);
  await page.waitForTimeout(350);
  assert.notEqual(await zoom(), '缩放 1.00×');
  await page.getByRole('button', {name: '重置', exact: true}).click();
  await page.mouse.click(600, 300, {button: 'right'});
  await page.waitForTimeout(350);
  assert.match(await zoom(), /0\.45/);
  await page.getByRole('button', {name: '重置', exact: true}).click();
  await page.keyboard.down('Shift');
  await page.mouse.click(600, 300);
  await page.keyboard.up('Shift');
  await page.waitForTimeout(350);
  assert.match(await zoom(), /0\.45/);
  await page.getByRole('button', {name: '重置', exact: true}).click();
  const beforePan = await coords();
  await page.mouse.move(600, 300);
  await page.mouse.down();
  await page.mouse.move(650, 350, {steps: 5});
  assert.ok(await canvas.evaluate(el => el.width < innerWidth), 'drag lowers sampling resolution');
  await page.mouse.up();
  await page.waitForTimeout(250);
  assert.notEqual(await coords(), beforePan);
  assert.equal(await canvas.evaluate(el => el.width), 2560, 'settling restores resolution');
  await page.mouse.wheel(0, -100);
  await page.waitForTimeout(250);
  assert.notEqual(await zoom(), '缩放 1.00×');
  for (const name of ['全景','海马谷','象谷','螺旋','迷你','星鱼','触须','针尖']) {
    await page.getByRole('button', {name, exact: true}).click();
    await page.waitForTimeout(100);
    assert.ok((await canvas.screenshot()).length > 5000, `${name} draws a nonempty canvas`);
  }
  await page.getByRole('button', {name: '海马谷', exact: true}).click();
  assert.notDeepEqual(await canvas.screenshot(), initial);
  for (const name of ['海岸','墨海','冰川','余烬','银盐']) {
    const button = page.getByRole('button', {name: `配色 ${name}`, exact: true});
    await button.click();
    assert.equal(await button.getAttribute('aria-pressed'), 'true');
  }
  const slider = page.getByRole('slider');
  await slider.focus();
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.getByRole('button', {name: '自适应', exact: true}).getAttribute('aria-pressed'), 'false');
  await page.getByRole('button', {name: '自适应', exact: true}).click();
  assert.equal(await page.getByRole('button', {name: '自适应', exact: true}).getAttribute('aria-pressed'), 'true');
  await page.getByRole('button', {name: '操作说明', exact: true}).click();
  assert.ok(await page.locator('#coast-help').isVisible());
  await page.getByRole('button', {name: '关闭说明', exact: true}).click();
  await page.getByRole('button', {name: '配色 海岸', exact: true}).click();
  await page.screenshot({path: '/tmp/infinite-coast-desktop.png'});
  await page.waitForTimeout(450);
  const saved = await coords();
  await page.reload();
  await page.waitForTimeout(500);
  assert.equal(await coords(), saved, 'restores saved view');
  for (const width of [390, 320]) {
    await page.setViewportSize({width, height: 844});
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'no horizontal page overflow');
    await page.getByRole('button', {name: '针尖', exact: true}).click();
    const controls = await page.getByRole('region', {name: '分形探索控件'}).boundingBox();
    assert.ok(controls.y + controls.height <= 844);
  }
  await page.setViewportSize({width: 390, height: 844});
  await page.getByRole('button', {name: '海马谷', exact: true}).click();
  await page.screenshot({path: '/tmp/infinite-coast-mobile.png'});
  const touchContext = await browser.newContext({viewport: {width: 390, height: 844}, isMobile: true, hasTouch: true, reducedMotion: 'reduce'});
  const touchPage = await touchContext.newPage();
  touchPage.on('pageerror', e => errors.push(e.message));
  await touchPage.goto(`${base}/demos/2026/infinite-coast/`);
  await touchPage.locator('astro-island[ssr]').waitFor({state: 'detached'});
  const cdp = await touchContext.newCDPSession(touchPage);
  await cdp.send('Input.dispatchTouchEvent', {type: 'touchStart', touchPoints: [{x: 150, y: 250, id: 1}, {x: 230, y: 250, id: 2}]});
  await cdp.send('Input.dispatchTouchEvent', {type: 'touchMove', touchPoints: [{x: 110, y: 250, id: 1}, {x: 270, y: 250, id: 2}]});
  const pinchZoom = await touchPage.locator('[data-coast-zoom]').innerText();
  assert.notEqual(pinchZoom, '缩放 1.00×');
  await cdp.send('Input.dispatchTouchEvent', {type: 'touchEnd', touchPoints: []});
  await touchPage.waitForTimeout(300);
  assert.equal(await touchPage.locator('[data-coast-zoom]').innerText(), pinchZoom, 'pinch release does not trigger a click zoom');
  await touchContext.close();
  const fallback = await browser.newPage();
  await fallback.addInitScript(() => { HTMLCanvasElement.prototype.getContext = () => null; });
  await fallback.goto(`${base}/demos/2026/infinite-coast/`);
  await fallback.getByText('当前浏览器不支持 WebGL，无法渲染分形。', {exact: true}).waitFor();
  await fallback.close();
  assert.deepEqual(errors, []);
  console.log('Infinite coast: desktop controls, presets, palettes, persistence, resolution recovery, narrow layouts, touch pinch and WebGL fallback passed.');
} finally { await browser.close(); }
