import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const base = process.env.BLOG_TEST_URL ?? 'http://127.0.0.1:4330';
const browser = await chromium.launch();
const errors = [];
try {
  const context = await browser.newContext({viewport: {width: 1280, height: 800}, deviceScaleFactor: 2, reducedMotion: 'reduce'});
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${base}/demos/2026/orbit/`);
  await page.locator('[data-orbit-ready=true]').waitFor();
  await page.getByRole('button', {name: '开始探索'}).click();
  const canvas = page.getByLabel('重力模拟画布');
  const button = name => page.getByRole('button', {name, exact: true});
  const count = () => page.locator('[data-orbit-count]').innerText();
  await button('暂停').click();
  const time = await page.locator('[data-orbit-time]').innerText();
  await page.waitForTimeout(200);
  assert.equal(await page.locator('[data-orbit-time]').innerText(), time);
  for (const [name, total] of [['星系',5],['双星',4],['八字',3],['弹弓',4],['空白',0]]) {
    await button(name).click();
    assert.equal(await count(), String(total), `${name} loads its bodies`);
    assert.equal(await button(name).getAttribute('aria-pressed'), 'true');
  }
  await button('恒星').click();
  await page.mouse.click(750, 300);
  await page.waitForTimeout(180);
  assert.equal(await count(), '1');
  assert.equal(await page.locator('[data-orbit-speed]').innerText(), '0.0');
  // Clicking the body at the same CSS coordinates must select it at DPR 2.
  await page.mouse.click(750, 300);
  await page.waitForTimeout(180);
  assert.equal(await count(), '1', 'high-DPR rendering and hit coordinates agree');
  await button('行星').click();
  await page.mouse.move(850, 420);
  await page.mouse.down();
  await page.mouse.move(880, 500, {steps: 6});
  await page.screenshot({path: '/tmp/orbit-prediction.png'});
  await page.mouse.up();
  await page.waitForTimeout(180);
  assert.equal(await count(), '2');
  assert.ok(Number(await page.locator('[data-orbit-speed]').innerText()) > 0);
  await button('删除选中').click();
  await page.waitForTimeout(180);
  assert.equal(await count(), '1');
  await button('轨迹').click();
  assert.equal(await button('轨迹').getAttribute('aria-pressed'), 'false');
  await button('轨迹').click();
  await button('跟随').click();
  assert.equal(await button('跟随').getAttribute('aria-pressed'), 'true');
  await button('跟随').click();
  await button('弹开').click();
  assert.equal(await button('弹开').getAttribute('aria-pressed'), 'true');
  await button('合并').click();
  await page.getByRole('slider').focus();
  await page.keyboard.press('ArrowRight');
  assert.equal(await page.getByRole('slider').inputValue(), '1.05');
  await button('继续').click();
  await page.waitForTimeout(350);
  assert.notEqual(await page.locator('[data-orbit-time]').innerText(), '0:00.0');
  await button('八字').click();
  await page.waitForTimeout(2200);
  assert.equal(await count(), '3');
  await page.screenshot({path: '/tmp/orbit-desktop.png'});
  await button('暂停').click();
  const before = await canvas.screenshot();
  await page.mouse.move(800, 300);
  await page.mouse.wheel(0, -200);
  await page.waitForTimeout(100);
  assert.notDeepEqual(await canvas.screenshot(), before, 'wheel changes the view');
  await page.mouse.down({button: 'right'});
  await page.mouse.move(850, 350, {steps: 5});
  await page.mouse.up({button: 'right'});
  assert.equal(await count(), '3', 'camera pan does not spawn');
  await button('复位').click();
  await button('清除').click();
  assert.equal(await count(), '0');
  for (const width of [390, 320]) {
    await page.setViewportSize({width, height: 844});
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await button('八字').click();
    const rect = await page.getByRole('region', {name: '轨道实验控件'}).boundingBox();
    assert.ok(rect.y + rect.height <= 844 && rect.x >= 0 && rect.x + rect.width <= width);
  }
  await page.setViewportSize({width: 390, height: 844});
  await button('继续').click();
  await page.waitForTimeout(1200);
  await page.screenshot({path: '/tmp/orbit-mobile.png'});
  const mobile = await browser.newContext({viewport: {width: 390, height: 844}, isMobile: true, hasTouch: true, reducedMotion: 'reduce'});
  const touch = await mobile.newPage();
  touch.on('pageerror', error => errors.push(error.message));
  await touch.goto(`${base}/demos/2026/orbit/`);
  await touch.getByRole('button', {name: '开始探索'}).click();
  await touch.getByRole('button', {name: '暂停', exact: true}).click();
  await touch.getByRole('button', {name: '空白', exact: true}).click();
  const cdp = await mobile.newCDPSession(touch);
  await cdp.send('Input.dispatchTouchEvent', {type: 'touchStart', touchPoints: [{x: 100,y: 240,id: 1},{x: 200,y: 240,id: 2}]});
  await cdp.send('Input.dispatchTouchEvent', {type: 'touchMove', touchPoints: [{x: 80,y: 270,id: 1},{x: 250,y: 270,id: 2}]});
  await cdp.send('Input.dispatchTouchEvent', {type: 'touchEnd', touchPoints: []});
  await touch.waitForTimeout(200);
  assert.equal(await touch.locator('[data-orbit-count]').innerText(), '0', 'pinch does not spawn');
  await touch.touchscreen.tap(170, 220);
  await touch.waitForTimeout(180);
  assert.equal(await touch.locator('[data-orbit-count]').innerText(), '1');
  await cdp.send('Input.dispatchTouchEvent', {type: 'touchStart', touchPoints: [{x: 100,y: 330,id: 3}]});
  await cdp.send('Input.dispatchTouchEvent', {type: 'touchCancel', touchPoints: []});
  await touch.waitForTimeout(180);
  assert.equal(await touch.locator('[data-orbit-count]').innerText(), '1', 'cancel does not spawn');
  assert.deepEqual(errors, []);
  console.log('Orbit browser checks passed: scenarios, launch, selection, pause, controls, DPR, camera, narrow layouts, pinch and pointer cancellation.');
} finally { await browser.close(); }
